/**
 * Apex Triad V1 — params de runtime (sem walletSize de lab).
 * Paridade labs/strategies/portfolio/apex-triad-v1/defaults.json.
 */

export const APEX_TRIAD_V1 = {
  baseBudget: 10,
  minShares: 1,
  entrySlippageMax: 0.02,
  minLiquidityRatio: 0.6,
  entryOrderType: 'GTC',
  exitOrderType: 'GTC',
  stopMinBid: 0.05,
  terminalEnabled: true,
  terminalMinSecondsLeft: 5,
  terminalMaxSecondsLeft: 30,
  terminalMaxDistAbs: 20,
  terminalMinAsk: 0.55,
  terminalMaxAsk: 0.82,
  terminalMaxSpread: 0.03,
  terminalMinOddsSum: 0.98,
  terminalMaxOddsSum: 1.06,
  terminalVelocityLookbackSecs: 5,
  terminalMaxAdverseSpotChange: 8,
  terminalMinObi: 0,
  terminalMaxVol: 99999,
  terminalVolLookbackSecs: 30,
  terminalMinFlips: 0,
  terminalMaxFlips: 9999,
  terminalFlipWindowSecs: 60,
  edgeEnabled: true,
  edgeWindowStart: 105,
  edgeWindowEnd: 31,
  edgeMinDistanceAbs: 40,
  edgeMinAsk: 0.08,
  edgeMaxAsk: 0.65,
  edgeMinEdge: 0.04,
  edgeMinDirectionalProb: 0.54,
  edgeMaxSpread: 0.06,
  edgeMinLiquidityRatio: 0.7,
  edgeBudgetFactor: 0.75,
  edgePriceAwareThreshold: 0.52,
  edgePriceAwareFactor: 0.5,
  minSigma: 10,
  sigmaMultiplier: 1,
  distanceWeight: 2,
  momentumWeight: 0.65,
  momentumSec: 6,
  slowMomentumSec: 18,
  slowMomentumWeight: 0.35,
  lagWeight: 0.45,
  volLookbackSec: 45,
  useBlackScholesProb: false,
  useObiDrift: false,
  useObiInScore: true,
  obiLevels: 5,
  obiScoreWeight: 0.35,
  profitLockEnabled: false,
  edgeStopBid: 0.18,
  edgeStopMinSecondsLeft: 16,
  edgeLateExitSec: 16,
  edgeLateExitMinBid: 0.64,
  edgeTrailAfterBid: 0.78,
  edgeTrailDrop: 0.1,
  reverseEnabled: true,
  reverseMaxAttempts: 1,
  edgeReverseMaxSecondsLeft: 60,
  edgeReverseMinSecondsLeft: 4,
  edgeReverseMinDistanceAbs: 10,
  terminalReverseMaxSecondsLeft: 8,
  terminalReverseMinSecondsLeft: 4,
  terminalReverseCrossDist: 0,
  reverseMaxAsk: 0.95,
  reverseMinLiquidityRatio: 0.6,
  reverseBudgetFactor: 1,
  dangerExitEnabled: true,
  dangerExitK: 0.3,
  dangerExitFloorSec: 4,
};

export const APEX_RUNTIME_KEYS = Object.freeze(Object.keys(APEX_TRIAD_V1));
